Repository shrey141102/Javascript-projects, pull requests merged in 2023-10, with the labels that each got.

#5 Drum Kit
  Drum Kit/background.jpg
  Drum Kit/index.html
  Drum Kit/readme.md
  Drum Kit/script/script.js
  Drum Kit/sounds/boom.wav
  Drum Kit/sounds/clap.wav
  Drum Kit/sounds/hihat.wav
  Drum Kit/sounds/kick.wav
  Drum Kit/sounds/openhat.wav
  Drum Kit/sounds/ride.wav
  Drum Kit/sounds/snare.wav
  Drum Kit/sounds/tink.wav
  Drum Kit/sounds/tom.wav
  Drum Kit/style/style.css
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#7 Added the Temperature converter project by Parmesh B
  README.md
  Temperature Converter/README.md
  Temperature Converter/demo.js
  Temperature Converter/index.html
  Temperature Converter/style.css
Labels: hacktoberfest-accepted

#9 Added BMI calculator
  BMI calculator/README.md
  BMI calculator/index.html
  BMI calculator/script.js
  BMI calculator/style.css
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#10 Temprature converter web application
  Temprature Converter/README.md
  Temprature Converter/drop.png
  Temprature Converter/dropDown.jpg
  Temprature Converter/index.html
  Temprature Converter/script.js
  Temprature Converter/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#24 Added Micro Editor in Browser
  Micro Code Editor in the Browser/index.html
  Micro Code Editor in the Browser/readme.md
  Micro Code Editor in the Browser/script.js
  Micro Code Editor in the Browser/style.css
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#27 E-com Website
  E-Commerce Website/Images.zip
  E-Commerce Website/Images/Cap1.png
  E-Commerce Website/Images/Cap2.png
  E-Commerce Website/Images/ContactUs.png
  E-Commerce Website/Images/Ferrari.jpg
  E-Commerce Website/Images/Ferrari1.png
  E-Commerce Website/Images/Jacket.png
  E-Commerce Website/Images/Logo.png
  E-Commerce Website/Images/Logo2.png
  E-Commerce Website/Images/Logo3.png
  E-Commerce Website/Images/Return.png
  E-Commerce Website/Images/Shipping.png
  E-Commerce Website/Images/Shoes.png
  E-Commerce Website/Images/Tshirt1.png
  E-Commerce Website/Images/Tshirt2.png
  E-Commerce Website/Images/Visa.png
  E-Commerce Website/Images/favicon-32x32.png
  E-Commerce Website/README.md
  E-Commerce Website/app.js
  E-Commerce Website/image-1.png
  E-Commerce Website/image-2.png
  E-Commerce Website/image-3.png
  E-Commerce Website/image-4.png
  E-Commerce Website/image-5.png
  E-Commerce Website/image.png
  E-Commerce Website/index.html
  E-Commerce Website/style.css
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#43 Add URL Shortener
  README.md
  URL Shortener/README.md
  URL Shortener/index.html
  URL Shortener/script.js
  URL Shortener/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#51 QR Code Generator
  QR Code Generator/QrCode.png
  QR Code Generator/README.md
  QR Code Generator/index.html
  QR Code Generator/index.js
  QR Code Generator/style.css
  README.md
  script.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#55 Added Weather App issue:#50
  README.md
  script.js
  weatherApplication/index.css
  weatherApplication/index.html
  weatherApplication/index.js
  weatherApplication/readme.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#57 update the saving list in localstorage part
  To-Do/script.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#58 Added Dynamic JS Quiz
  Dynamic JS Quiz/index.html
  Dynamic JS Quiz/jsquiz.js
  Dynamic JS Quiz/readme.md
  Dynamic JS Quiz/stylesheet.css
  README.md
  script.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#60 3d website
  3dWeb/.gitignore
  3dWeb/dist/.gitkeep
  3dWeb/dist/assets/index-60c247ed.css
  3dWeb/dist/assets/index-690acdb9.js
  3dWeb/dist/assets/index-690acdb9.js.map
  3dWeb/dist/index.html
  3dWeb/package-lock.json
  3dWeb/package.json
  3dWeb/readme.md
  3dWeb/src/index.html
  3dWeb/src/script.js
  3dWeb/src/style.css
  3dWeb/static/.gitkeep
  3dWeb/vite.config.js
  README.md
  script.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#62 added new Weather app project
  README.md
  script.js
  skycast (weather app)/app.js
  skycast (weather app)/images/images.jpg
  skycast (weather app)/images/nat.jpg
  skycast (weather app)/index.html
  skycast (weather app)/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#65 added Dynamic online resume and updated main script.js
  DYNAMIC ONLINE RESUME/.DS_Store
  DYNAMIC ONLINE RESUME/CODE_OF_CONDUCT.md
  DYNAMIC ONLINE RESUME/CONTRIBUTING.md
  DYNAMIC ONLINE RESUME/LICENSE
  DYNAMIC ONLINE RESUME/README.md
  DYNAMIC ONLINE RESUME/basic-resume-light/index.html
  DYNAMIC ONLINE RESUME/basic-resume-light/style.css
  DYNAMIC ONLINE RESUME/index.html
  DYNAMIC ONLINE RESUME/resume-dark/index.html
  DYNAMIC ONLINE RESUME/resume-dark/style.css
  DYNAMIC ONLINE RESUME/script.js
  DYNAMIC ONLINE RESUME/style.css
  Image Background remover/README.md
  Image Background remover/index.html
  Image Background remover/mail.js
  Image Background remover/style.css
  script.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#68 Added note taking application and updated main script.js
  Note Taking Application/index.html
  Note Taking Application/script.js
  Note Taking Application/style.css
  Palindrome Checker/index.html
  Palindrome Checker/script.js
  Palindrome Checker/style.css
  script.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023
